### ISSUE TITLE
The output of this library

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/diff#14]
**Deciding the output of this library**

Main points to look at:
- Extensible(in case we need to extend the format, but without breaking the previous version).
- Integration with different tools.

### Classification

Our diff library will have three types of change classification:
- Breaking change
- Non-breaking change
- Unclassified
        Some changes (for example: JSON schema object in message payload) can be changed or extended with external libraries, in which case it becomes hard to document every change as breaking/non-breaking.
        Thus, some changes will be considered `unclassified`. Which we are basically telling the user to handle the changes themselves.

### Output

```json
{
  "breaking": [
    {
      "type": "breaking",
      "action": "delete",
      "entity": "<the root level property name>",
      "path": "<JSON-path>",
      "before": "<the value of deleted field>"
    }
  ],
  "nonbreaking": [
    {
      "type": "nonbreaking",
      "action": "edit",
      "entity": "<the root level property name>",
      "path": "<JSON-path>",
      "before": "<the value of original field>",
      "after": "<the value of edited field>"
    }
  ],
  "unclassified": [],
  "breakingDifferencesFound": true
}
```

- `type` will tell what type of change it is. While it is evident from the JSON itself, it might help in our wrapper function.
- `action` will have
    - `add` - Something has been added
    - `delete` - Something has been deleted
    - `edit` - Something has been edited
- `entity` will contain the root level property in which the change has been introduced. This might be helpful when we want to get a change in a certain field.
- `path` - The JSON path where the change has been made.
- `before` - The original data 
- `after` - The changed data

So, this will be the output of our library. I made this issue because there might be some points I may have missed, so I would like your feedback on the output :)

### Real world example:

firstSpec.yml
```yml
asyncapi: 2.1.0
info:
    title: Title
servers:
    production:
        protocol: ‘http’
```

secondSpec.yml

```yml
asyncapi: 2.1.0
info:
    title: Title
servers:
    production:
        protocol: ‘https’
```
Diff output:

```json
{
    "breaking" : [
    {
        "type": "breaking",
        "action": "modify",
        "entity": "servers",
        "path": "/servers/production/protocol",
        "before": "http",
        "after": "https"
        
}
],
    "nonbreaking": [],
    "unclassified": [],
    "breakingDifferencesFound": true
}
```

**Comment by magicmatatjahu** [comment]
Please share the issue on the slack. More people will see your thoughts :)

**Comment by aayushmau5** [comment]
> breaking, nonbreaking and unclassified items should have before and after information. Maybe you have this in mind, but you forgot to add the fields in example

Yup. Will add those in the examples :)

> could you provide some example based on real data for the shape of output, it will be great to understand for someone what exactly is entity and path :)

Sure. Will update the issue example in a bit.

> I have concerns about splitting the items to the arrays like breaking, nonbreaking and unclassified. I prefer way to have only changes array with all mentioned items with breaking, non-breaking etc changes

Can you elaborate on your concern? The reason why I felt like splitting them is if any user wants to see only the breaking change, they can just get the `breaking` array instead of going through the whole output, and checking whether the `type` is breaking or not. But I'm open to your idea of getting it all inside a single `changes` array, but more inclined towards splitting them right now. So, I need to know what are your concerns about that. Thanks :) 

> Have in mind that we will operate not only on objects/properties but also on array, so we should also consider changes in items (indexes) of array, so maybe changed item should have also index property to inform which index of array is changed

Oh yeah, you are right. Will update that. Thanks again.

> However have in mind, that users have also possibility to create the extensions in spec

For this, I'm thinking of a way to override/extend our standard file. The user can provide their own `standard` file which will overwrite the matching fields from the user provided standard. 

```json
 {
    "type": "breaking",
    "action": "edit",
    "path": "servers",
    "children": [
          {
            "type": "breaking",
            "action": "edit",
            "path": "servers/development",
            "children": [
              {
                   "type": "breaking",
                   "action": "edit",
                   "path": "servers/development/protocol"
              }
             ]
          }
    ]
  },
```

This is an interesting idea.

But while classifying the parent as `breaking` or `non-breaking` may seem "falsy" I guess. Because let's say `servers` has more than one server, than it can be that one server has breaking change and another has non-breaking(Splitting breaking/non-breaking might help here). 

But I will look into this idea as well. Thanks for this suggestion.

**Comment by magicmatatjahu** [comment]
> Can you elaborate on your concern? The reason why I felt like splitting them is if any user wants to see only the breaking change, they can just get the breaking array instead of going through the whole output, and checking whether the type is breaking or not. But I'm open to your idea of getting it all inside a single changes array, but more inclined towards splitting them right now. So, I need to know what are your concerns about that. Thanks :)

I used the wrong word 😅  Any concerns and problems I don't have, but for me, as the developer, the normal single `changes` array will be better, and then package can export also helper function to change the output from `changes` to the corresponding arrays - similar approach like we have in our https://github.com/asyncapi/app-relations-discovery library. We will return the default syntax from main function, and then will have a several functions which will change the output to another syntax. Probably in implementation in this library, you will add everything to the temporary `changes` array and at the end you will filter the items to the `breaking` etc arrays :) Lets see what other people think about that.

> For this, I'm thinking of a way to override/extend our standard file. The user can provide their own standard file which will overwrite the matching fields from the user provided standard.

it should be normal JS object, not path to the file. If you will use the fs under the hood, then users won't be able to use the package in the browser. So really, have it in the mind :) Also, the overriding feature will be used to the next version of the spec - e.g. we will publish 3.0.0 so then we will use the mapping from 2.0.0 version and only extend it, so it's very important to treat mapping as normal JS object.  

> But while classifying the parent as breaking or non-breaking may seem "falsy" I guess. Because let's say servers has more than one server, than it can be that one server has breaking change and another has non-breaking(Splitting breaking/non-breaking might help here).

Yeah, you're right here and thanks for good example. Maybe we should have also additional metadata in mapping to tell how deep breaking changes are breaking changes - like in your example, changing protocol is breaking change to the corresponding server, but not to the servers object. What do you think?

**Comment by aayushmau5** [comment]
> I used the wrong word sweat_smile Any concerns and problems I don't have, but for me, as the developer, the normal single changes array will be better, and then package can export also helper function to change the output from changes to the corresponding arrays - similar approach like we have in our https://github.com/asyncapi/app-relations-discovery library. We will return the default syntax from main function, and then will have a several functions which will change the output to another syntax. Probably in implementation in this library, you will add everything to the temporary changes array and at the end you will filter the items to the breaking etc arrays, so filtering we can export to the standalone function :) Lets see what other people think about that.

Yup. This is one of the milestones of this library. Just like the asyncapi `parser` provides a list of helper methods, we will have a `wrapper` class which will incorporate a bunch of helper methods that do exactly this :D. So I think we can go with putting all the changes inside a `changes` array then.

> it should be normal JS object, not path to the file. If you will use the fs under the hood, then users won't be able to use the package in the browser. So really, have it in the mind :) Also, the overriding feature will be used to the next version of the spec - e.g. we will publish 3.0.0 so then we will use the mapping from 2.0.0 version and only extend it, so it's very important to treat mapping as normal JS object.

Oh yeah, you are right. Will think in terms of object, then. 

> Maybe we should have also additional metadata in mapping to tell how deep breaking changes are breaking changes - like in your example, changing protocol is breaking change to the corresponding server, but not to the servers object. What do you think?

Sorry, I don't understand it :( Can you elaborate on this `metadata`? Like how would this look like, and how would this work?

**Comment by magicmatatjahu** [comment]
> Sorry, I don't understand it :( Can you elaborate on this metadata? Like how would this look like, and how would this work?

Information in some shape which will inform that if (eg) `servers/{serverStage}/protocol` has breaking change, then `servers/{serverStage}` has also breaking change, but `servers` won't.

**Comment by derberg** [comment]
- shouldn't `path` be `jsonPointer`?
- approach with children seems cleaner, I like it
- not sure if we need `breakingDifferencesFound` if at the end we will have helper methods, I guess `hasBreakingChanges()` helper would be there. No strong opinion here though.

Ready to open a PR?

**Comment by aayushmau5** [comment]
> shouldn't path be jsonPointer?
Yeah. Is there any difference between JSON path and JSON pointer? 

> not sure if we need breakingDifferencesFound if at the end we will have helper methods, I guess hasBreakingChanges() helper would be there. No strong opinion here though.

Yeah, that makes sense. Will move it inside our helper function.

> approach with children seems cleaner, I like it

The main concern I have right now is what if we have some deep nested change? Won't then the children approach might look unnecessary.

Here's an example:

Suppose there's a change inside `channels`, `production`, `message`, `payload`, `item`

Then the change might look like this:

```json
{
  "changes": [
    {
      "path": "/channels",
      "children": {
        "production": {
          "children": {
            "message": {
              "children": {
                "payload": {
                  "children": {
                    "item": {
                      "type": "breaking"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  ]
}
```
(Removed some extra infos for the sake of verbosity).

What do you think?

**Comment by magicmatatjahu** [comment]
> > not sure if we need breakingDifferencesFound if at the end we will have helper methods, I guess hasBreakingChanges() helper would be there. No strong opinion here though.

> Yeah, that makes sense. Will move it inside our helper function.

Probably better will be return the output as instance of class, where you will have a another helper functions, not only `hasBreakingChanges()`.

> The main concern I have right now is what if we have some deep nested change? Won't then the children approach might look unnecessary.

If you look on the changes as json, then you can think that's unnecessary, but if you will operate on it as JS object, then you will be able to conclude that it is a better solution. Also if we go with instance of class as output, we can create helper function which will transform output with `children` fields to the flattened output :)

**Comment by aayushmau5** [comment]
> Have in mind that we will operate not only on objects/properties but also on array, so we should also consider changes in items (indexes) of array, so maybe changed item should have also index property to inform which index of array is changed

For this, We have two secnarios here:

1. Change occurred directly inside the array:
For this, we will have an `index` property where the change has been occured.

```json
{
  "tags": [1,2,3]
}
```


```json
{
  "tags": [1,2]
}
```

Output:
```json
{
  "path": "/tags",
  "index": 2,
  "action": "remove",
  "before": 3
}
```

2. Change occurred inside an object present inside an array:

```json
{
  "tags": [
    {
      "name": "name",
      "description": "description"
    }
  ]
}

```

```json
{
  "tags": [
    {
      "name": "name",
    }
  ]
}

```
Output:
```json
{
  "path": "/tags/0/description",
  "action": "remove",
  "before": "description"
}
```

Notice the `path` for this output. 

What do you think about this?

**Comment by aayushmau5** [comment]
> If you look on the changes as json, then you can think that's unnecessary, but if you will operate on it as JS object, then you will be able to conclude that it is a better solution. Also if we go with instance of class as output, we can create helper function which will transform output with children fields to the flattened output :)

Then I guess it all comes down to which output the user wants to see by default and the performance of finding the correct place for a particular path. I will look into it. Thanks :)

**Comment by derberg** [comment]
JSON with children is definitely not human-friendly, say what you want but a flat structure with a clear JSONPointer is better to read for a human. But humans should not look at the raw output but the output prepared by some fancy UI or CLI. I think the focus on coding experience is more important here.


> Yeah. Is there any difference between JSON path and JSON pointer?

JSONPointer has a clear spec and its purpose is to point exactly to a specific part of JSON, and JSONPath is more than that. We use JSONPointer in the parser to point to a specific part of the JSON that has parsing errors.

**Comment by aayushmau5** [comment]
Went with having all changes inside a `changes` array. And now, the helper methods will be used to modify the output.
