### ISSUE TITLE
When using "allOf", breaking changes are not detected.

### ISSUE THREAD

**Issue by JFCote** [asyncapi/diff#164]
#### Describe the bug

When using `allOf` in a model, breaking changes are not detected.

#### How to Reproduce

Using these 2 spec files:

[spec1.yaml](https://gist.github.com/JFCote/f8b647d64e2fc07f7e71b0c62d4d44e3)
[spec1.yaml](https://gist.github.com/JFCote/6d72e66d5a9838fb3da918027d307178)

Breaking change rules:

[Breaking Change Rules](https://gist.github.com/JFCote/05c12b2409b2e6d9f3186ece671ede6f)

I then use this command:
`asyncapi diff ./spec1.yaml ./spec2.yaml -o breaking-changes-override.json -t breaking -f json`

Notice that no breaking changes are detected even if we deleted a required statement.

#### Expected behavior
The breaking changes should be detected by this section of the rules:

```json
"/components/schemas/*/required": {
    "add": "breaking",
    "remove": "breaking",
    "edit": "breaking"
  },
  "/components/schemas/*/required/*": {
    "add": "breaking",
    "remove": "breaking",
    "edit": "breaking"
  },

**Comment by aayushmau5** [comment]
@JFCote The way you defined the override file is incorrect.

For a change to be detected at "/something/else/*", we also need to define the changes for "/something" as well as "/something/else". The process is explained here: https://github.com/asyncapi/diff/pull/19

I think the docs needs to communicate it better. And better yet, if somehow we could detect "/something/else/*" directly without having those intermediate classifications. I'll start thinking of improving the lib in that way :)

For now, here's the classification you need to put in your override file:

```json
"/components/schemas/*": {
  "add": "non-breaking",
  "remove": "breaking",
  "edit": "breaking"
},
"/components/schemas/*/allOf": {
  "add": "breaking",
  "remove": "breaking",
  "edit": "breaking"
},
"/components/schemas/*/allOf/*": {
  "add": "breaking",
  "remove": "breaking",
  "edit": "breaking"
},
"/components/schemas/*/allOf/*/required": {
  "add": "breaking",
  "remove": "breaking",
  "edit": "breaking"
},
"/components/schemas/*/allOf/*/required/*": {
  "add": "breaking",
  "remove": "breaking",
  "edit": "breaking"
},
```

Thanks!

**Comment by JFCote** [comment]
Thanks! That did the trick!!

**Comment by derberg** [comment]
seems to be solved
