### ISSUE TITLE
Have the option to skip the parsing step

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/diff#22]
We should have an option to skip the parsing step, that we if we have a parsed document we can just provide it, and perform the diff on it.

I'm thinking of something like:

```js
function main(firstDocument, secondDocument, config) {
    if(config.skipParsing) // skip parsing
}
```

**Comment by onbit-syn** [comment]
@aayushmau5 Good thought. Just curious what will be the situation when a user will provide the parsed document? As far I know, the library will be used in a `CLI or Async API Studio` and both will assume that the `diff` library will parse the document.

**Comment by derberg** [comment]
how about `config.parse` and have parsing disabled by default? so far use case for CLI and Studio is that these tools will parse AsyncAPI file before invoking diff

**Comment by magicmatatjahu** [comment]
For me disabling parsing should be done in case where someone want to make diff on a raw AsyncAPI document not in case when someone pass the parsed doc (but we should also support case with passing the parsed doc to the diff function). As I user I want to make the diff on the raw data like:

```yaml
channels:
  channel:
    publish:
      message:
        $ref: '#/components/messages/message'
```

So If I change the ref to the message, then I should have information that value for `$ref` is changed - in first iteration of `diff` lib we will have information that `publish.message` object is changed and it can create misunderstanding from user perspective.

**Comment by derberg** [comment]
> As I user I want to make the diff on the raw data like

you mean you want to pass not AsyncAPI file or AsyncAPIDocument object? or?

> So If I change the ref to the message, then I should have information that value for $ref is changed - in first iteration of diff lib we will have information that publish.message object is changed and it can create misunderstanding from user perspective.

sorry I did no get that 🤔

**Comment by magicmatatjahu** [comment]
@derberg Sorry for not clarification 😄  I wanna pass the raw AsyncAPI document to the diff function (without parsing) and check the differences on it. Why? Let's check the example.

We can have simple AsyncAPI doc with refs inside the content like:

```yaml
asyncapi: 2.1.0
info: ...
channels:
  channel1:
    publish:
      message:
        $ref: '#/components/messages/message'
  channel2:
    publish:
      message:
        $ref: '#/components/messages/message'
```

then I will change the refs to the `'#/components/messages/message-second'`. What I will see on the first version of the `diff` lib? I will see the Information that `/channels/channel1/publish/message` and `/channels/channel2/publish/message` are changed, not the `$ref` point, but whole object. As a user (but in this case as dev) I would like to see the changes between the documents like in git (changed lines). 

Of course see the changes based on raw documents will be helpfully only for the people which will write the AsyncAPI documents, but the users which use the AsyncAPI documents to check the documentation of the application will prefer the diff output based on the parsed specification. 

This is a rare use case, but we should consider it and perhaps implement it.

**Comment by magicmatatjahu** [comment]
> just to make sure I get it right -> you want diff to support passing raw AsyncAPI file and that it is not parsed with the parser?

Yes.

> By principle this should be a super simple and lightweight library

What is a problem with this use case? You can parse raw AsyncAPI document by `JSON.parse` (or if it's a YAML by `json-yaml` package) and perform diff like with parsed document.

**Comment by derberg** [comment]
> Yes.

another question, why we use parser here anyway?

> What is a problem with this use case? You can parse raw AsyncAPI document by JSON.parse (or if it's a YAML by json-yaml package) and perform diff like with parsed document.

wait, what are we talking about here 😄 I'm talking that it would be nice to have asyncapi parser excluded from the diff entirely, but first need to know what parser is here for. And you now talk about parsing it with JSON.parse.

**Comment by aayushmau5** [comment]
> another question, why we use parser here anyway?

@derberg During my proposal, I assumed that this library will be used as a standalone application, therefore I incorporated the parsing step inside this library. 

But now that you say that the data may come parsed already, I think the parser might not be needed then. 

What are your thoughts?

**Comment by derberg** [comment]
@aayushmau5 are you using any of the features of the parser? its API?

**Comment by aayushmau5** [comment]
Not really. The parser is just there so that I get the parsed asyncapi document. That's all.

**Comment by derberg** [comment]
then yeah, imho just 👇🏼 

![](https://media.giphy.com/media/keaA1N2HOQfLF3NrXb/giphy-downsized.gif)

@magicmatatjahu you see any meaningful use case to keep it?

**Comment by magicmatatjahu** [comment]
@derberg @aayushmau5 I see only for (as @aayushmau5  wrote) `a standalone application` but... I remember situation when I wanted remove the parser from the react-component (with this same purpose - to reduce the weight of component) and everyone was against it. I see some people's thinking is suddenly changing 😆 

Also as you know or not, we can also introduce two function `diff` and `parseAndDiff` - on the second case with parser onboard and by this we will have treeshaking of the parser, but it can be done as followups if someone raise such a issue, at the moment we can go without parser.

**Comment by aayushmau5** [comment]
So I think for now, I'm going to remove the parser. If in the future, the need arises, we can make another function like `parseAndDiff` which will have the parser built-in.

**Comment by magicmatatjahu** [comment]
To be clear, `diff` "needs" because currently it operates on parsed and validated AsyncAPI doc, if you provide broken/undereferenced spec you will have broken output.

btw, in AsyncAPI we have something like `AsyncAPIWithoutParsre` component which hasn't parser.

**Comment by aayushmau5** [comment]
> btw, in AsyncAPI we have something like AsyncAPIWithoutParsre component which hasn't parser.

I can use this to validate the input data. Pretty good suggestion. Thanks :)

So, right now. I'll just
1. remove the parser functions.
2. add the `AsyncAPIWithoutParse` function to validate the input data.

**Comment by aayushmau5** [comment]
btw where's this component? @magicmatatjahu 
Like in which library?

**Comment by derberg** [comment]
`diff` should not care if file is valid or not, if it is broken or not. Validation as a prerequisite. CLI and UI will handle that. 

dereferences input - yeah, this makes sense but it should not be a reason to include parser in `diff`. Again, this is a prerequisite, that must be documented, like in case of document validity. It is not `diff` duty to handle dereferencing. In case other use diff in places other than CLI or Studio, they might just use dereferencing library independently if they want.

current use case for diff is to use it in CLI and Studio, let us not extend scope just because we think something would be cool. Add parser and validation only if there are valid use cases from users that will integrate the library

sorry but what is `AsyncAPIWithoutParse`, I'm missing some context?

**Comment by magicmatatjahu** [comment]
> sorry but what is AsyncAPIWithoutParse, I'm missing some context?

Component which hasn't parser onboard and you must pass the parsed spec to the component. I give it as example how to handle the parser "problem" in the `diff`.

@aayushmau5 https://github.com/asyncapi/asyncapi-react/blob/next/library/src/containers/AsyncApi/Standalone.tsx here, but it's written in React so it won't be useful for you.
