### ISSUE TITLE
`npm install @asyncapi/diff` fetches the original TS source code instead of compiled JS output

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/diff#33]
#### Describe the bug
Was trying this library out for the demo, and imports were not working. Looking at `node_modules` directory, the fetched data is this repo's TS source code instead JS ouput.

#### How to Reproduce
`npm install @asyncapi/diff`

#### Expected behavior
The imports should work as expected and the code fetched from npm should be the compiled JS source code.

I'm thinking that some scripts may be missing from the `package.json` file.

@derberg this needs immediate attention.

**Comment by aayushmau5** [comment]
I think it's the `prepublishOnly` script that's missing from `package.json`.

**Comment by jonaslagoni** [comment]
> I think it's the `prepublishOnly` script that's missing from `package.json`.

@aayushmau5 you are right, looks like the rest of the setup is working as expected (took it for a spin). That script ensures that the correct files are present (`./lib`) when publishing the package, as they are not present otherwise (because of git-ignore).

**Comment by aayushmau5** [comment]
cool. Thanks for confirming @jonaslagoni . Will make a PR to fix this.
