### ISSUE TITLE
Diff2Html - Allowing users to see diff in HTML

### ISSUE THREAD

**Issue by boyney123** [asyncapi/diff#66]
#### Reason/Context

I came across this tool https://diff2html.xyz/, and after playing around with it, it's a great way to show diff using HTML.

I wonder if people would find it useful to be able to use AsyncAPI diff tool to output the diff into HTML?

Maybe a new command, that output a directory with the files in it so they can host them, or view them etc...

## Why we need this improvement?

Guess we don't I just think it would be nice to offer users another output vs the cli/console.

## How will this change help?

Maybe attract more people to use the lib?

## What is the motivation? 

Some great work done here, just wanted to see if we could extend it :)

**Comment by aayushmau5** [comment]
Awesome! @boyney123 
We(Lukasz and I) discussed [here](https://github.com/asyncapi/cli/pull/135#discussion_r755864078) that this library should support different types of output, and I have been thinking about making an issue right after merging the CLI PR. 

Thanks for suggesting the resources for generating the HTML output. I will look into that :)

**Comment by boyney123** [comment]
No problem @aayushmau5 , happy to help if/when you come to look at it :)
