### ISSUE TITLE
Integrating diff in an action

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/diff#79]
#### Description

The plan is to have this library as a github action, where a change in an AsyncAPI document present in a repo can tell us what kind of changes we are making. Helpful with info like breaking changes, etc.

- **What changes have to be introduced?**
  None in the library itself.

This issue will act as the medium to have discussion about the action, what kind of action we want, what should the format of the output, etc.

I have a few questions:

- What kinds of input do we want?
   For example, what files should the action check? What type of change should the action output?
- What kind of output do we want?
- Where do we want the output to be?
- Where do we want to source code to live? (In the org, or my personal github account?)

I'll be working on this issue.

CC @jonaslagoni

**Comment by gabormagyar** [comment]
I'll give this one a go for the initial implementation. I'm thinking I will copy what https://github.com/mvegter/openapi-diff-action does, only instead of a `.sh` entry point I'll have a small `.js` script that loads two files and calls this lib.

I definitely think this should be under the name _asyncapi/openapi-diff-action_, can someone help create it?

**Comment by jonaslagoni** [comment]
@gabormagyar start with a personal GH repo, then once you see fit you can donate it, same as others do: https://github.com/asyncapi/community/discussions/223

That is probably the best way to do it 🙂

**Comment by magicmatatjahu** [comment]
> or have generic action for AsyncAPI CLI

I'm for that 🚀  We already have too many repositories and it is better to have one project for generic actions.

**Comment by derberg** [comment]
many repos is not a problem, or at least I think we should avoid this argument as something that should block an idea. 
I just think it is simply much easier for community to use one CLI action as people will be able to do more things with just one  action

**Comment by aayushmau5** [comment]
> wouldn't it be better to have documentation in readme that explain how to create a workflow that can do diff using AsyncAPI CLI? or have generic action for AsyncAPI CLI?

I never thought of that :facepalm:. Having action using CLI is so much better.

**Comment by aayushmau5** [comment]
So, I'm guessing we should close this issue, and create one in CLI repo?
