### ISSUE TITLE
Add support for Markdown output

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/diff#84]
This library currently supports JSON, & YAML output. 
We need to support Markdown output as well.

Check https://github.com/asyncapi/diff/issues/75

Suggested [solution](https://github.com/asyncapi/diff/issues/75#issuecomment-1014275955):

> Headings are names of changes, and then under each heading I guess you get a table of changes? could be nicely handled with [IonicaBizau/json2md](https://github.com/IonicaBizau/json2md), so you just first slightly modify the default JSON output that you get as input for Markdown, and then run it through json2md to get markdown. No complicated Markdown templating needed, you only need to add some props to JSON

### The format of md output

Subject to change, but my initial thoughts are as follows:

- If user request a `breaking`, `non-breaking` or `unclassified` changes:

### Breaking Changes

| **Action** | **Path**          | **Before** | **After** | **isArrayIndex** |
| ---------- | ----------------- | ---------- | --------- | ---------------- |
| `remove`   | `/servers/google` | `{}`       |           | false            |
| `add`      | `/server/google/protocol`            |      | `http`    | false            |
| `edit`     | `/server/google/something/1`            | `some value`     | `new value`    | true             |

- If user requests all changes

### All changes

| **Type**       | **Action** | **Path**                     | **Before**   | **After**   | **isArrayIndex** |
| -------------- | ---------- | ---------------------------- | ------------ | ----------- | ---------------- |
| `breaking`     | `remove`   | `/servers/google`            | `{}`         |             | false            |
| `non-breaking` | `add`      | `/server/google/protocol`    |              | `http`      | false            |
| `unclassified` | `edit`     | `/server/google/something/1` | `some value` | `new value` | true             |

If you have other suggestions, drop them below :)

**Comment by shivensinha4** [comment]
I'd love to work on this! Following up on our slack discussion, the structure of a Markdown diff will be similar to [this](https://gist.github.com/shivensinha4/ed86f714ebc028c641b010747103c425), as it's hard to display large objects in the `after` and `before` columns of the table in a lucid format. The type of the data inside the dropdowns can be configured to be either JSON or YAML using the `markdownSubtype` option.

The WIP can be found at https://github.com/shivensinha4/diff, and I'll create a PR once the subtype option is added :)

**Comment by aayushmau5** [comment]
@shivensinha4 Looking forward to the PR :slightly_smiling_face:

**Comment by derberg** [comment]
@shivensinha4 how is it going, do you need some help?

**Comment by shivensinha4** [comment]
Sorry for the delay! Got caught up in some stuff. I'm done with most of the code, will look for and make any documentation edits soon : )
